language: python
sudo: required

env:
  global:
    - TX_BRANCH="develop"
    - TX_TAG="txpull"
    - TX_COMMIT_TRANSLATIONS=true

install:
  - pip install transifex-client
  
script:
  - echo "Run something"
  
after_success:
  - echo "Success"
  - provider: script
    script: ./tx.sh push
    on:
      branch: $TX_BRANCH
  - echo "Success 2"
    
