language: python

addons:
  apt:
    update: true
    
env:
  global:
    - TX_BRANCH="develop"
    - TX_TAG="txpull"
    - TX_COMMIT_TRANSLATIONS=true

install:
  - pip install transifex-client

script:
  - echo "Run something"

deploy:
  # Push source file for translations on builds on $TX_BRANCH
  - provider: script
    script: chmod +x ./tx.sh push
    on:
      branch: $TX_BRANCH

  # Pull translation files on builds started from a git tag called $TX_TAG
  # It may also commit and push the changes back to Github if the env var
  # $TX_COMMIT_TRANSLATIONS is set to true.
  - provider: script
    script: chmod +x ./tx.sh pull
    clean_up: false
    on:
      tags: true
