language: python

env:
  global:
    - TX_BRANCH="develop"
    - TX_TAG="txpull"
    - TX_COMMIT_TRANSLATIONS=true
    
before_install:
  - rvm install 2.1.5
  
install:
  - pip install transifex-client

script:
  - echo "Run something"
  - echo "$PWD"

deploy:
  - skip_cleanup: true
  # Push source file for translations on builds on $TX_BRANCH
  - provider: script
    script: ./tx.sh push
    on:
      branch: $TX_BRANCH

  # Pull translation files on builds started from a git tag called $TX_TAG
  # It may also commit and push the changes back to Github if the env var
  # $TX_COMMIT_TRANSLATIONS is set to true.
  - provider: script
    script: ./tx.sh pull
    on:
      tags: true
