language: python

env:
  global:
    - TX_BRANCH="develop"
    - TX_TAG="txpull"
    - TX_COMMIT_TRANSLATIONS=true

install:
  - pip install transifex-client
  
script:
  - echo "Run something"
  
after_success:
  - echo "Success"
  - chmod +x ./deploy.sh && sh ./deploy.sh
  - echo "Success 2"
    
