language: python

env:
  global:
    - TX_BRANCH="develop"
    - TX_TAG="txpull"
    - TX_COMMIT_TRANSLATIONS=true

install:
  - pip install transifex-client

script:
  - echo "Run something"
  - echo "$PWD"

after_success: chmod +x ./deploy.sh
