language: python

env:
  global:
    - TX_BRANCH="devel"
    - TX_TAG="txpull"
    - TX_COMMIT_TRANSLATIONS=true

install:
  - pip install transifex-client

script:
  - echo "Run something"

deploy:
  # Push source file for translations on builds on $TX_BRANCH
  - provider: script
    script: ./tx.sh push
    on:
      branch: $TX_BRANCH

  # Pull translation files on builds started from a git tag called $TX_TAG
  # It may also commit and push the changes back to Github if the env var
  # $TX_COMMIT_TRANSLATIONS is set to true.
  - provider: script
    script: ./tx.sh pull
    on:
      tags: true
