language: generic # no-frills build

sudo: required

env:
  global:
    - TX_BRANCH="develop"
    - TX_TAG="txpull"
    - TX_COMMIT_TRANSLATIONS=true

install:
  - pip install virtualenv
  - virtualenv ~/env
  - source ~/env/bin/activate
  - pip install transifex-client

script:
  - echo "Run something"
  
deploy:
  skip_cleanup: true
  # Push source file for translations on builds on $TX_BRANCH
  - provider: script
    script: ./tx.sh push
    on:
      branch: $TX_BRANCH

  # Pull translation files on builds started from a git tag called $TX_TAG
  # It may also commit and push the changes back to Github if the env var
  # $TX_COMMIT_TRANSLATIONS is set to true.
  - provider: script
    script: ./tx.sh pull
    on:
      tags: true    
