language: python

env:
  global:
    - TX_BRANCH="develop"
    - TX_TAG="txpull"
    - TX_COMMIT_TRANSLATIONS=true

install:
  - pip install transifex-client
  
script:
  - echo "Run something"
  
after_success:
  - echo $TRAVIS_BRANCH
  - chmod +x ./.tx.sh
  - test $TRAVIS_BRANCH = $TX_BRANCH &&
    ./.tx.sh push
  - test $TRAVIS_TAG = true &&
    ./.tx.sh pull
  - echo "Success"
  - STR="My string"
  - [[ $STR =~ .*My.* ]] &&
    echo "It's there!!!!!"
