language: python
node_js:
  - "9"
sudo: false

env:
  global:
    - TX_BRANCH="develop"
    - TX_TAG="txpull"
    - TX_COMMIT_TRANSLATIONS=true
    
before_install:
  - npm i -g npm
  
install:
  - pip install transifex-client
  
script:
  - echo "Run something"
  
after_success:
  - chmod +x ./.tx.sh
  - test $TRAVIS_BRANCH = $TX_BRANCH &&
    ./.tx.sh push
  #- ./.tx.sh pull
